Hw02 express
Ex0rc1st/goit-nodejs-homework-rest-api pull request #1
Opened 2023-01-24 10:51 UTC by Ex0rc1st

2023-01-24 10:57 UTC, KhYulian requested changes
Потрібні правки

2023-01-24 10:57 UTC, KhYulian commented on models/contacts.js
> +};
Усе що в models/contacts.js - це сервіси. Створіть папку services і помістіть файл туди. Файл перейментуйте у contactsServices

2023-01-24 10:57 UTC, KhYulian commented on controllers/contacts.js
> +const contactsOperation = require("../models/contacts");
Зробоіть деструктуризацію, щоб не писати кожного разу contactsOperation. ТАкож це не операції, а сервіси contactsServices

2023-01-24 11:54 UTC, Ex0rc1st commented on controllers/contacts.js
> +const contactsOperation = require("../models/contacts");
Зауваження виправленно.

2023-01-24 11:55 UTC, Ex0rc1st commented on models/contacts.js
> +};
Зауваження виправленно.

2023-01-27 11:38 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-27 11:39 UTC, merged